name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: conan
      run: conan install . -s build_type=Release --install-folder=cmake-build-release --profile=gcc_x86_64 && cd cmake-build-release
    - name: cmake
      run: cmake -DCMAKE_BUILD_TYPE=Release -G "Unix Makefiles" ..
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
